
import { JetBrains_Mono, Cinzel } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import PageTransition from "@/components/page_transition";
import StairTransition from "@/components/stair_transition";
import { Suspense } from "react";
import Loading from "./loading";
import Door from "@/components/door"
import Reveal from "@/components/reveal";

const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  new Promise(resolve => setTimeout(resolve, 3000));
  return (
    <html lang="en" className="h-full w-full relative">
      <Reveal>
        <body
          className={`${cinzel.className} font-mono antialiased h-screen w-screen self-center overflow-y-scroll flex flex-col relative z-1`}
        >
          <Header className="" />
          <Suspense fallback={<Loading />}>
            {children}
          </Suspense>
        </body>
      </Reveal>
    </html>
  );
}
