import { JetBrains_Mono, Cinzel } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import PageTransition from "@/components/page_transition";
import StairTransition from "@/components/stair_transition";
import { Suspense } from "react";
import Loading from "./loading";
import Door from "@/components/door";
import Footer from "@/components/footer";
import Script from "next/script";

const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

const jetbrain = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Sun Minus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  new Promise((resolve) => setTimeout(resolve, 3000));
  return (
    <html lang="en" className="h-full w-full relative">
      <head>
        {/* CẤY GHÉP BỌ THEO DÕI UMAMI VÀO ĐÂY */}
        <Script
          src="https://nnhieu-umami.duckdns.org/script.js"
          data-website-id="1b6fae1a-6414-4831-b0cb-cce0e4f7eb58"
          strategy="afterInteractive"
        />
      </head>
      <body
        className={`${jetbrain.className} font-mono antialiased h-screen w-screen self-center overflow-y-scroll flex flex-col relative z-1`}
      >
        <Header className="" />
        <Suspense fallback={<Loading />}>{children}</Suspense>
        <Footer />
      </body>
    </html>
  );
}
