app = "portfolioo-141"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "rolling"
  wait_timeout = "10m"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  [http_service.concurrency]
    type = "requests"
    soft_limit = 100
    hard_limit = 150
  [http_service.http_options]
    idle_timeout = 600
  [[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"