apiVersion: v1
kind: Service
metadata:
  name: portfolioo141-service
  labels:
    app: portfolioo141
spec:
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3000
      protocol: TCP
  selector:
    app: portfolioo141