name: Oracle Cloud CD
permissions:
  contents: read
  actions: read

on:
  workflow_run:
    workflows: [Docker Image CI]
    types:
      - completed

jobs:
  deploy_images:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Download Docker Image tag
        uses: actions/download-artifact@v4
        with:
          name: tag
          path: image_tag/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read Tag into Variable
        id: read_tag
        run: |
          TAG=$(cat image_tag/tag)
          if [[ ! "$TAG" =~ ^[a-zA-Z0-9.-]+$ ]]; then
            echo "CRITICAL SECURITY ERROR: Invalid tag format. Possible injection detected."
            exit 1
          fi
          EOF=$(cat /proc/sys/kernel/random/uuid)
          echo "IMAGE_TAG<<$EOF" >> $GITHUB_ENV
          echo "$THE_TAG" >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV
          echo "Securely loaded tag for deployment."

      - name: Deploy to Oracle Cloud
        uses: appleboy/ssh-action@v1.0.3
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USERNAME }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          envs: IMAGE_TAG
          script: |
            echo "Initiating deployment for hieu18022004/portfolioo141:${{IMAGE_TAG}}"
            docker pull hieu18022004/portfolioo141:${{IMAGE_TAG}}
            kubectl set image deployment/p-deployment portfolioo141=hieu18022004/portfolioo141:$IMAGE_TAG

          
  
