name: GitOps Manifest Updater
permissions:
  contents: read
  actions: read

on:
  workflow_run:
    workflows: [Docker Bridge]
    types:
      - completed

jobs:
  deploy_images:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    
    steps:
      - name: Download Docker Image tag
        uses: actions/download-artifact@v4
        with:
          name: tag
          path: image_tag/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read Tag into Variable
        id: read_tag
        run: |
          TAG=$(cat image_tag/tag)
          if [[ ! "$TAG" =~ ^[a-zA-Z0-9.-]+$ ]]; then
            echo "CRITICAL SECURITY ERROR: Invalid tag format. Possible injection detected."
            exit 1
          fi
          EOF=$(cat /proc/sys/kernel/random/uuid)
          echo "IMAGE_TAG<<$EOF" >> $GITHUB_ENV
          echo "$TAG" >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV
          echo "Securely loaded tag for deployment."

      - name: Checkout Manifest Repository Securely
        uses: actions/checkout@v4
        with:
          repository: hieu180230/portfolioo141-k8s
          ssh-key: ${{ secrets.AGROCD }}
          path: .

      - name: Update Image Tag and Push
        run: |
          git remote set-url origin git@github.com:hieu180230/portfolioo141-k8s.git
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

          yq e '(.spec.source.helm.parameters[] | select(.name == "frontend.tag")).value = "${{ env.IMAGE_TAG }}"' -i application-fe.yaml
          yq e '(.spec.source.helm.parameters[] | select(.name == "backend.tag")).value = "${{ env.IMAGE_TAG }}"' -i application-be.yaml

          if [ -n "$(git status --porcelain)" ]; then
            git add application.yaml
            git commit -m "chore: update application image tags to ${{ env.IMAGE_TAG }} via CI"
            git push origin main
            echo "Tag changed, manifest pushed!"
          else
            echo "Tag not changed!"
          fi
          
          echo "Securely pushed new tag to GitOps repository."

          
  
