name: Docker Bridge
permissions:
  contents: read
  
on:
  push:
    branches: [ "main" ]
    paths:
      - 'portfolio/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'portfolio/**'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.tag_generator.outputs.IMAGE_TAG }}

    steps:
    - name: Set current date as variable
      run: |
        DATE=$(date +'%Y-%m-%d')
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        echo "IMAGE_TAG=$DATE-$SHORT_SHA" >> $GITHUB_ENV
        
    - name: checkout
      uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: login to docker hub
      run: |
        docker login -u hieu18022004 -p ${{secrets.DOCKER_HUB}}

    - name: Build and Push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: ./portfolio/
        file: ./portfolio/Dockerfile
        platforms: linux/arm64 # The exact architecture your cloud needs
        push: true
        tags: hieu18022004/portfolioo141:${{ env.IMAGE_TAG }}
    
    - name: Write Docker Image tag to file
      run: |
        mkdir -p ./image_tag
        echo ${{ env.IMAGE_TAG }} > ./image_tag/tag
        
    - name: Upload Docker Image tag to Artifact
      uses: actions/upload-artifact@v4
      with:
        name: tag
        path: image_tag/
