name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  publish_images:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: buid image
      run: docker build ./portfolio/ --t hieu18022004/portfolioo141:$(date +%s)
    - name: push to docker hub
      run: docker push hieu18022004/portfolioo141:$(date +%s)
