name: Application Integration

on:
  push:
    branches: [ "dev" ]
    paths:
      - 'portfolio/**'
      - 'portfolio-be/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'portfolio/**'
      - 'portfolio-be/**'
      - '.github/workflows/**'

jobs:
  security_scan:
    name: TruffleHog Secret Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
  
  frontend_ci:
    name: Next.js CI
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: [security_scan]
    defaults:
      run:
        working-directory: ./portfolio
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ./portfolio/package-lock.json
      
      - name: Install Deps
        run: npm ci
      
      - name: Run ESLInt
        run: npm run lint

      - name: Test Next.js Build
        run: npm run build

  backend_ci:
    name: Rust API CI
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: [security_scan]
    defaults:
      run:
        working-directory: ./portfolio-be
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./portfolio-be -> target
        
      - name: Check Formatting
        run: cargo fmt -- --check

      - name: Run Clippy Linter
        run: cargo clippy

      - name: Run Tests
        run: cargo test
    